/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import control.*;

/**
 *
 * @author ld_si
 */
public class ServidorUI extends javax.swing.JFrame {
    private static Servidor server;
    private static ServidorUI janelaControl;

    /**
     * Creates new form servidorUI
     */
    public ServidorUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jButtonAceitar = new javax.swing.JButton();
        jButtonNegar = new javax.swing.JButton();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Solicitação de Retirada");
        getContentPane().add(jLabelTitulo);
        jLabelTitulo.setBounds(214, 90, 361, 44);

        jLabelId.setForeground(new java.awt.Color(255, 255, 255));
        jLabelId.setText("ID:");
        getContentPane().add(jLabelId);
        jLabelId.setBounds(270, 210, 240, 14);

        jLabelNome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNome.setText("Nome: ");
        getContentPane().add(jLabelNome);
        jLabelNome.setBounds(270, 230, 280, 20);

        jButtonAceitar.setText("Aceitar");
        jButtonAceitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceitarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAceitar);
        jButtonAceitar.setBounds(470, 460, 90, 23);

        jButtonNegar.setText("Negar");
        jButtonNegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNegarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNegar);
        jButtonNegar.setBounds(220, 460, 90, 23);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/Fundo2.png"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 800, 600);

        setSize(new java.awt.Dimension(800, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceitarActionPerformed
        try {
            server.tratamento("Aceito");
            server = new Servidor();
            new Thread() {
                @Override
                public void run() {
                    iniciar(server, janelaControl);
                }

            }.start();
        } catch (IOException ex) {
            Logger.getLogger(ServidorUI.class.getName()).log(Level.SEVERE, null, ex);
        }
  
        janelaControl.setVisible(false);
    }//GEN-LAST:event_jButtonAceitarActionPerformed

    private void jButtonNegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNegarActionPerformed
        try {
            server.tratamento("Negado");
            server = new Servidor();
            new Thread() {
                @Override
                public void run() {
                    iniciar(server, janelaControl);
                }

            }.start();
        } catch (IOException ex) {
            Logger.getLogger(ServidorUI.class.getName()).log(Level.SEVERE, null, ex);
        }
 
        janelaControl.setVisible(false);
    }//GEN-LAST:event_jButtonNegarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void mostrar() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServidorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServidorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServidorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServidorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ServidorUI janela = new ServidorUI();
                janelaControl = janela;
                janela.setVisible(false);
                server = new Servidor();
                new Thread(){
                    public void run(){
                        iniciar(server,janela);
                    }
                    
                }.start();
                
                
            }
        });
    }
    
    public static void iniciar(Servidor server, ServidorUI janela){
        new Thread() {
                   public void run() {
                       server.start(janela);
                    }
        }.start();
    }
    public void setJLabelId(String id){
        this.jLabelId.setText(id);
    }
    public void setJLabelNome(String nome){
        this.jLabelNome.setText(nome);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceitar;
    private javax.swing.JButton jButtonNegar;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelTitulo;
    // End of variables declaration//GEN-END:variables
}
